-- ============================================================
-- Parcel / Transfer — Supabase schema
-- Run this in the Supabase SQL editor for your project.
-- ============================================================

-- 1. Table storing each transfer's metadata
create table if not exists public.transfers (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  files jsonb not null default '[]'::jsonb, -- [{ name, relativePath, size, path, type }]
  total_bytes bigint not null default 0,
  download_count int not null default 0,
  recipient_email text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists transfers_code_idx on public.transfers (code);
create index if not exists transfers_expires_at_idx on public.transfers (expires_at);

-- 2. Row Level Security
-- This app is "anyone with the code can access it" by design, like WeTransfer,
-- so the anon key is allowed to insert new transfers and read any transfer by code.
-- There is no listing/browsing of all transfers from the client.
alter table public.transfers enable row level security;

drop policy if exists "anon can insert transfers" on public.transfers;
create policy "anon can insert transfers"
  on public.transfers for insert
  to anon
  with check (true);

drop policy if exists "anon can read a transfer by code" on public.transfers;
create policy "anon can read a transfer by code"
  on public.transfers for select
  to anon
  using (true);

-- 3. RPC to atomically bump the download counter (called after a successful pickup)
create or replace function public.increment_download_count(transfer_code text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.transfers
  set download_count = download_count + 1
  where code = transfer_code;
$$;

grant execute on function public.increment_download_count(text) to anon;

-- 4. Storage bucket for the actual files
-- Create it here (idempotent) — you can also do this from Storage > New bucket in the dashboard.
--
-- IMPORTANT — real file size ceiling: Supabase enforces a *global* file size
-- limit in Storage Settings (dashboard: Storage > Settings > Global file size
-- limit) that applies on top of anything set here. On the Free plan this
-- cannot exceed 50MB, no matter what you set below. On Pro and up you can
-- raise it to as much as 500GB. Set file_size_limit below to whatever you've
-- configured as the global limit (or lower, to restrict this bucket further).
insert into storage.buckets (id, name, public, file_size_limit)
values ('parcels', 'parcels', false, 53687091200) -- 50GB; only takes effect if your plan's global limit allows it
on conflict (id) do update set file_size_limit = excluded.file_size_limit;

-- Storage policies: anon can upload into the bucket and can read objects
-- (reads happen via short-lived signed URLs generated by the app, not public URLs).
drop policy if exists "anon can upload parcels" on storage.objects;
create policy "anon can upload parcels"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'parcels');

drop policy if exists "anon can read parcels" on storage.objects;
create policy "anon can read parcels"
  on storage.objects for select
  to anon
  using (bucket_id = 'parcels');

-- ============================================================
-- 5. Optional: scheduled cleanup of expired parcels
-- Requires the pg_cron extension (Database > Extensions in the dashboard).
-- This deletes expired rows; you'll still want a periodic job (e.g. a
-- Supabase Edge Function on a cron trigger) to also remove the matching
-- files from the 'parcels' storage bucket, since SQL alone can't touch Storage.
-- ============================================================
-- create extension if not exists pg_cron;
-- select cron.schedule(
--   'delete-expired-transfers',
--   '0 * * * *', -- hourly
--   $$ delete from public.transfers where expires_at < now(); $$
-- );
